### ISSUE TITLE
How to use the Attack demo?

### ISSUE THREAD

**Issue by memory009** [WoodwindHu/GSDA#1]
Hello, I use the method you provided, put the .mat provided by you in the Data folder, and then run ''python attack.py'', but the hd_loss/cd_loss/curv_loss and attack success are both 0 in the result ,As shown below  
[Picture](https://github.com/memory009/undergraduate/blob/main/figure/reproduce%EF%BC%88GSDA_error%EF%BC%89.png)

**Comment by WoodwindHu** [comment]
Sorry for the late reply, I also reproduce this error, something must have gone wrong when I reorganized the code. However, I've been struggle into works these day. I'll fix this bug in next week.

**Comment by WoodwindHu** [comment]
I found it's cause by the argument of 'spectral_offset', I've fixed the bug.
