### ISSUE TITLE
How to train with PointNet++

### ISSUE THREAD

**Issue by memory009** [WoodwindHu/GSDA#2]
I tried to reproduce the code in GeoA3, and found in the issue that you raised the question of "how to train with PointNet++", how did you solve it in the end?

**Comment by WoodwindHu** [comment]
Pointnet++'s code is included in Model/pointnet2, you could set "--arch PointNetPP" to attack PointNet++.

**Comment by memory009** [comment]
Thank you for your reply, I will try it this week~
